### ISSUE TITLE
关于SEO 话说怎么不考虑使用Nuxt 3呢？  看了下你博客就只有首页被收录

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ADKcodeXD/Myblog-Vue3viteTs#1]

**Comment by ADKcodeXD** [comment]
哈哈，其实有想过用nuxt3 。但是感觉迁移起来有点麻烦，迁移的时候也遇到了一些问题，后面就摆了（
目前seo只用到了prerender.io来进行处理。收录的问题我也不太清楚百度该怎么去处理sitemap还有索引之类的，总而言之就是放上去了他不收录~以后学习下吧XD

**Comment by Yakumo-Yukari** [comment]
> 哈哈，其实有想过用nuxt3 。但是感觉迁移起来有点麻烦，迁移的时候也遇到了一些问题，后面就摆了（ 目前seo只用到了prerender.io来进行处理。收录的问题我也不太清楚百度该怎么去处理sitemap还有索引之类的，总而言之就是放上去了他不收录~以后学习下吧XD

233333
