### ISSUE TITLE
大佬可以出一个接口文档吗？

### ISSUE THREAD

**Issue by ycfeng666** [ADKcodeXD/Myblog-Vue3viteTs#2]
准备用node写一个后端，非常感谢

**Comment by ADKcodeXD** [comment]
可以 等我有空我看看用apifox啥的生成一个

**Comment by ADKcodeXD** [comment]
链接：https://www.apifox.cn/apidoc/shared-59ec557e-e1fe-4a14-940f-ff5d1960342c 访问密码：gVFWQ71E

**Comment by StarryO1224** [comment]
问下还有吗 这个分享失效了 非常感谢

**Comment by ADKcodeXD** [comment]
> 
https://www.apifox.cn/apidoc/shared-16f4d985-0c34-4b32-88e1-c5b5de9be288
有的，不过该api文档是自动生成的有些简陋。

**Comment by StarryO1224** [comment]
> > 
> 
> https://www.apifox.cn/apidoc/shared-16f4d985-0c34-4b32-88e1-c5b5de9be288 有的，不过该api文档是自动生成的有些简陋。

感谢
